# Site settings
title: DerekKen Blog
SEOTitle: 邓瑞康的博客  |  Derek Ken's Blog
header-img: img/home-bg.jpg
email: mail361service@163.com
description: "邓瑞康，Derek Ken，undergraduate student，senior at Nankai University，南开大学本科在读，intern at NBJL(Nankai Baidu Joint Laboratory)，南开百度联合实验室实习，soccer devotee(both on the pitch & in front of the screen)，球迷，时不时踢踢野球 | 这里是 @DerekKen邓瑞康 的个人博客，与你一起点滴积累，踏实前行，发现更大的世界。"
keyword: "Derek Ken, 邓瑞康, 南开大学, 软件工程, Derek, Ken, DerekKen , 互联网, 邓瑞康的博客, DerekKen Blog, 博客, 个人博客"
url: "https://DerekKen.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     DerekKen
zhihu_username:     DerekKen
github_username:    DerekKen
twitter_username:   DerekKen
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins of Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]
gems:
  - jemoji


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: DerekKen

# Netease setttings
netease_comment: false
# netease_comment: true

# Uyan setttings
uyan_comment: true

# Analytics settings
# Baidu Analytics
ba_track_id: 96c664732516db4d16de28619ed4d523 # DerekKen's 百度统计 代码追踪id

# Google Analytics
ga_track_id: 'UA-106767476-1'            # DerekKen's Format: UA-xxxxxx-xx 
ga_domain: derekken.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，读读好书，踢踢野球 <br /> The journey of a thousand miles begins with one step."
sidebar-avatar: /img/avatar_DerekKen.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this threshold



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [

    # {
         # title: "冯总",
         # href: "https://weibo.com/u/1630913862"
    # },{
         # title: "juju",
         # href: "https://user.qzone.qq.com/337612083"
    # },{
         # title: "粗神_Cuppix",
         # href: "https://music.163.com/#/user/home?id=253527733"
    # },{
         # title: "xvv",
         # href: "https://user.qzone.qq.com/986947390"
    # },{
         # title: "WHY",
         # href: "https://user.qzone.qq.com/2952203838"  
    # },{
         # title: "Mia_Zhang",
         # href: "https://user.qzone.qq.com/191715415"
    # },{
         # title: "Ruby",
         # href: "https://user.qzone.qq.com/549644724"
    # },{
         # title: "Jeremy_Liu",
         # href:  "https://user.qzone.qq.com/1368528587"
    # },{
         # title: "My_Devotion",
         # href: "https://user.qzone.qq.com/136692698"
    # },{
         # title: "晓熙",
         # href: "https://user.qzone.qq.com/474045174"
    # },{
         # title: "陈龙",
         # href: "https://weibo.com/u/1919548964"
    # },{
         # title: "junjun",
         # href: "https://user.qzone.qq.com/295722661"    
    # },{
         # title: "Streammy°",
         # href: "https://user.qzone.qq.com/864008019"
    # },{
         # title: "汀兰",
         # href: "https://user.qzone.qq.com/934919206"
    # },{
        # title: "哈利",
        # href: "https://weibo.com/u/5376588694"
    # },{
        # title: "胖娃儿",
        # href: "https://user.qzone.qq.com/310988425"
    # },{
        # title: "敬铭",
        # href: "https://user.qzone.qq.com/759049225"
    # },{
        # title: "黄叔(su)叔(ru)",
        # href: "https://user.qzone.qq.com/594403295"
    # }
    
    
    {
         title: "粗神Cuppix的音乐工作室",
         href: "https://music.163.com/#/user/home?id=253527733"
    },{
         title: "本博客支持emoji，表情代码戳这里",
         href: "https://www.webpagefx.com/tools/emoji-cheat-sheet"
    },{
         title: "emoji supported,cheat-sheet here",
         href: "https://www.webpagefx.com/tools/emoji-cheat-sheet"       
    }

 ]
